version: "3.7"

services:
  rethinkdb:
    image: rethinkdb:latest
    ports:
      - 28015:28015
      - 8080:8080
    volumes:
      - /data:/data
    command: rethinkdb --bind all --bind-http all --initial-password ${RETHINKDB_PASSWD}
