version: "3.7"

services:
  redis:
    image: redis:alpine
    hostname: redis-service
    container_name: redis-service
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
